### ISSUE TITLE
onUnregister Problem

### ISSUE THREAD

**Issue by FLecorps** [wbadam/autocomplete-extension#1]
Hello,

We have a client-side crash as soon as the AutoComplete extension is unregistered (AutocompleteExtensionConnector.onUnregister() Method).

It seems that the getTextField() returns a NPE in this case...

We are working on Vaadin 8.0.0.rc1 (last version).

Can you have a look at that?

It would be great, because your extension is awesome (light & easy to use) and we plan to use it for our search-textfields.

Thanks a lot,
Best Regards,
Fred

**Comment by wbadam** [comment]
Hi Fred,

Thanks for letting me know about this issue.

It seems that the parent connector is not available any more when `onUnregister()` is called. As a solution, I store the actual TextField widget and let the connector's methods access that directly instead.

Will include this fix in the next release soon.

Regards,
Adam

**Comment by FLecorps** [comment]
Hi Adams,

Many thanks for your very-fast fix.

Best regards,
Fred
