### ISSUE TITLE
extending with autoucomplete-extension broke setSizeFull for edit field

### ISSUE THREAD

**Issue by tamoler** [wbadam/autocomplete-extension#12]
to fix this i added
>.autocomplete-textfield{
		width : 100%;
	}

**Comment by realulim** [comment]
I had the same problem. I had an editable Grid and the TextField in the Grid was limited in size to an arbitrary width (about 300 pixels or so), when I installed an AutoComplete Extension to it. Adding the above CSS fixed the issue, so many thanks to tamoler and perhaps this can/should be fixed?
