### ISSUE TITLE
Other views "hang" when using with vaadin4spring sidebar

### ISSUE THREAD

**Issue by jonmartinsolaas** [wbadam/autocomplete-extension#14]
[demo.zip](https://github.com/wbadam/autocomplete-extension/files/916461/demo.zip)

After updating to latest (commit a73f11837d6f2a81cf9eaf3e0b9d3b14fbac43e0) my application hangs when navigating away from a view using autocomplete-extension to another view.

When the autocomplete component is removed from the app, navigation works.

Added a minimalistic project to illustrate.

Edit: Reloading the hanging view makes it load correctly.

**Comment by wbadam** [comment]
Additional DOM elements were removed incorrectly on TextField detach.

**Comment by jonmartinsolaas** [comment]
Problem solved, thank you!
