### ISSUE TITLE
A problem when using autocomplete-extension with expanded textfield

### ISSUE THREAD

**Issue by alexxxnik** [wbadam/autocomplete-extension#16]
Hello!

Thanx for great staff. It's very usefull for me. But I have a problem. I have a HorizontalLayout with 2 components on it. First is TextField with 100% width and it has expanding option when adding to layout. All looks good when shown initially, but after I select any value from suggestions list my expanded textfield increases in size and moves second component outside the layout.

**Comment by wbadam** [comment]
Hi, I couldn't reproduce the issue so far. Could you send me a simple reproducible example? Also, which version of the add-on are you using?

In case you are developing a search field, you can take a look at the [SearchBox add-on](https://vaadin.com/directory#!addon/searchbox), that is based on the autocomplete extension.

**Comment by sebastianrothbucher** [comment]
Thanks for the great addon!! You can reproduce this spec. issue via a textfield width 100% inside a vertical layout width 100% - the text field stays small. You could solve this by creating a span instead of a div in createWrapper() (or formatting .autocomplete-textfield to display: inline)
