### ISSUE TITLE
Reflection error "object is not an instance of declaring class"

### ISSUE THREAD

**Issue by ctliv** [wbadam/autocomplete-extension#18]
Implementing the basic "planetField" example on Vaadin 8.1.3 (except that the "suggestPlanet" method returns a fixed list of planet names, to make it even simpler) when the client calls the server the following error is triggered:

```
com.vaadin.server.ServerRpcManager$RpcInvocationException: Unable to invoke method getSuggestion in org.vaadin.addons.autocomplete.client.AutocompleteExtensionServerRpc
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:159)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:116)
        ... (omitted)
Caused by: java.lang.IllegalArgumentException: object is not an instance of declaring class
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at com.vaadin.server.ServerRpcManager.applyInvocation(ServerRpcManager.java:155)
        ... 167 more
```

The error is thrown by Vaadin's [ServerRpcManager](https://github.com/vaadin/framework/blob/8.1.3/server/src/main/java/com/vaadin/server/ServerRpcManager.java) method invocation at line 155.

Widgetset is compiled (in fact, the call is sent to the server). The extension is normally included as dependency using maven:

```
		<dependency>
			<groupId>org.vaadin.addons</groupId>
			<artifactId>autocomplete</artifactId>
			<version>0.2.2</version>
		</dependency>
```

Code is super-easy:

```
public class TestSuggestUI extends UI {
	
	TextField planetField = new TextField();

	@Override
	protected void init(VaadinRequest request) {
		AutocompleteExtension<String> planetExtension = new AutocompleteExtension<>(planetField);		
		planetExtension.setSuggestionGenerator(this::suggestPlanet);		
		setContent(planetField);
	}
	
	private List<String> suggestPlanet(String query, int cap) {
		ArrayList<String> planets = new ArrayList<>();
		planets.add("Mercury");
		planets.add("Venus");
		planets.add("Earth");
		planets.add("Mars");
		planets.add("Jupiter");
		planets.add("Saturn");
		planets.add("Uranus");
		planets.add("Neptune");
        return planets.stream().filter(p -> p.contains(query)).limit(cap).collect(Collectors.toList());
    }
	
}
```

Any hint?

**Comment by wbadam** [comment]
Hi, I couldn't reproduce the issue but
- do you see a server side exception earlier on, e.g. when the extension is instantiated? Perhaps `No interface T extends ServerRpc found in the class hierarchy.`?
- an older version of the add-on may be stuck in your project, or perhaps multiple versions? Try to make sure there is only one version and perhaps clean the maven repo so that everything will be downloaded again.

Let me know if any of these help pinpointing the issue.

**Comment by ctliv** [comment]
Hello, thanks for your response.

The answer to both questions is "no" but, actually, I forgot to mention that the UI was a portlet deployed to Liferay 7 (OSGi based). After the fact that you could not reproduce the issue, I focused on OSGi and made the error away just exporting your addon's packages.

Now I'm trying to make the addon work...

**Comment by wbadam** [comment]
Closing this since it was an OSGi issue.

**Comment by mltpz** [comment]
Dear all,
I have the same issue. Is there any workaround?
The only solution I have found is to re-install Liferay: after re-installation, my portlet works fine.
But it is not acceptable to re-install Liferay...
