### ISSUE TITLE
Provide a source and javadoc artifacts

### ISSUE THREAD

**Issue by stadler** [wbadam/autocomplete-extension#19]
It would be very useful if this project would also provide a source and/or javadoc jar artifact.
This would allow API users to directly see the Javadoc of the api within their IDE.
Because currently, one has to visit this github repo manually to see the documentation of your API, which is quite cumbersome.

This should be quite easy to do using the following maven plugins:
* https://maven.apache.org/plugins/maven-javadoc-plugin/
* https://maven.apache.org/plugins/maven-source-plugin/

Regards, Jacques

**Comment by wbadam** [comment]
Hi, I was under the impression that the add-on contains sources as well, but you are right and they were not included. Please use version 0.2.3 and up which now includes sources and javadoc as well.
