### ISSUE TITLE
Allow suggestions to be shown for empty TextField

### ISSUE THREAD

**Issue by ayo7** [wbadam/autocomplete-extension#21]
Hi!

The goal is to show suggestions whenever textfield receives a focus, even if it is empty.
Although triggering of suggestion list visibility is easily achieved by using TextField FocusListener, it's not working if current input is empty.
I believe there no reason to forcibly hide suggestions list for empty input as this case can be (and I believe should be) controlled by SuggestionGenerator: so if you don't want suggestions on empty string - just return empty list by your SuggestionGenerator.
I've noticed two places where empty value prevents suggestions to be shown.

`AutocompleteExtensionConnector.java:217`
```java
    private void onInput(InputEvent event) {
        if (!textField.getValue().isEmpty()) {
            showSuggestionsFor(textField.getValue(),
                    getState().suggestionDelay);
        } else {
            suggestionList.hide();
        }
    }

....

    private void showSuggestionsFor(String text, int delayMillis) {
        if (Objects.nonNull(text) && !text.isEmpty()) {
            suggestionTimer
                    .schedule(text, suggestionList.getQuery(), delayMillis);
        } else {
            suggestionTimer.cancel();
        }
    }

```

Thanks!

**Comment by wbadam** [comment]
Hi,
Thank you for your feedback. I can't think of the reason I didn't want to allow empty suggestions initially. Your reasoning seems correct so I'll include this feature shortly.
