### ISSUE TITLE
API for the suggestion list size

### ISSUE THREAD

**Issue by FLecorps** [wbadam/autocomplete-extension#4]
This is not an issue but an enhancement proposal:
 
Similar to the 
    AutocompleteExtension::setSuggestionDelay(int delayMillis) 
method, it would be great to have this one:
    AutocompleteExtension::setSuggestionListSize(int size) 

Thanks,
Fred

**Comment by wbadam** [comment]
That should've been there all along, the variable exists in state but somehow forgot about wiring it up. Will fix it, thanks!

**Comment by FLecorps** [comment]
Can't see your change in async-generatot branch... did I miss something?
Thanks

**Comment by wbadam** [comment]
I didn't push because I wanted to test beforehand. Now you can find it in master.

**Comment by FLecorps** [comment]
Can you merge it into the async branch as well?

Thanks!
Fred

**Comment by wbadam** [comment]
Sure, I merged master and committed the changes to async-generator branch

**Comment by FLecorps** [comment]
Great!
Thanks.
